<a href="https://colab.research.google.com/github/omerbecors/Corpus2GeoRAG/blob/main/Graph_n_Geocoding/Graph_and_Geocoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#

In [2]:
from transformers import pipeline, AutoModelForTokenClassification, AutoTokenizer
from geopy.geocoders import Nominatim
from time import sleep as wait
from tqdm import tqdm

import networkx as nx
import pandas as pd
import numpy as np

In [3]:
%%bash
rm -rf LM4GeoAI
git clone https://github.com/EtzionR/Corpus2GeoRAG.git

Cloning into 'Corpus2GeoRAG'...

In [4]:
df = pd.read_csv('Corpus2GeoRAG/examples/entities_table.csv')

print(f'Dataframe shape: {df.shape}\n\n')

df.head()

Dataframe shape: (1002, 8)

,entity_group,score,word,start,end,Source,Index,Text
0,MISC,0.999741,Russian,25,32,12 (song),0,"""12"" is a 2022 single by Russian rap artist Mo..."
1,PER,0.481228,Morgenshtern,44,56,12 (song),0,"""12"" is a 2022 single by Russian rap artist Mo..."
2,ORG,0.658771,Telegram,122,130,12 (song),0,"""12"" is a 2022 single by Russian rap artist Mo..."
3,MISC,0.674395,12,179,181,12 (song),0,"""12"" is a 2022 single by Russian rap artist Mo..."
4,PER,0.575160,Morgenshtern,21,33,12 (song),1,"""12"" is dedicated to Morgenshtern's younger br..."

In [7]:
df.entity_group.value_counts()

entity_group
LOC     370
MISC    328
PER     155
ORG     149
Name: count, dtype: int64

In [12]:
loc_entities = list(df[df.entity_group=='LOC'].word.unique())

print(f'{len(loc_entities)} LOC entities found by the NER model\n')

95 LOC entities found by the NER model

In [13]:
loc_entities[:5]

['Ukraine', 'Russia', 'Darnytskyi District', 'Kyiv', 'Kharkiv']

In [14]:
geolocator = Nominatim(user_agent="GeoAI_Wikipedia_Corpus_to_GeoGraph", timeout=10)
geolocator

In [16]:
example = 'נטף, ישראל'

geocoding_output = geolocator.geocode(example)

geocoding_output

Location(נטף, מועצה אזורית מטה יהודה, נפת ירושלים, מחוז ירושלים, ישראל, (31.8320125, 35.0679987, 0.0))